logging:
  level:
    shop.game: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace





spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
  datasource:
    url: jdbc:mariadb://localhost:3306/gameshop
    username: gameuser
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  messages:
    basename: messages, errors

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

file:
  dir: D:/project/game/src/main/resources/static/assets/img/games/